# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  gateway:
    image: yarpgateway
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 7979:7979
      - 8989:8989
